name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Allows you to run this workflow calling it from another workflow
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v3
    
      - name: Run commands
        run: |
          "C:\Program Files\MATLAB\R2023a\bin\matlab.exe" -batch "openProject(pwd); checkTask;"

      - name: Archive check results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: code-issues
          path: checkResults.json
          
  test:
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v3
    
      - name: Run commands
        run: |
          "C:\Program Files\MATLAB\R2023a\bin\matlab.exe" -batch "openProject(pwd); testTask('github');"
          
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          fail_on: "test failures"
          action_fail: true
          files: |
            results.xml
