name: CI

env:
  MATLAB_VER: R2023a

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Allows you to run this workflow calling it from another workflow
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    runs-on: matlab
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:  
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ secrets.REPO_READ_TOKEN }}

      - name: Cache MATLAB build files
        uses: actions/cache@v3
        with:
          key: matlab-buildtool
          path: |
            buildUtilities/.buildtool

      - name: Run MATLAB command
        run: |
          &"$env:ProgramFiles\MATLAB\$env:MATLAB_VER\bin\matlab.exe" -batch "openProject(pwd); cd('buildUtilities'); buildtool check"

      - name: Archive check results
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: code-issues
          path: checkResults.json

  test:
    runs-on: matlab
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:  
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ secrets.REPO_READ_TOKEN }}

      - name: Cache MATLAB build files
        uses: actions/cache@v3
        with:
          key: matlab-buildtool
          path: |
            buildUtilities/.buildtool

      - name: Run MATLAB command
        run: |
          &"$env:ProgramFiles\MATLAB\$env:MATLAB_VER\bin\matlab.exe" -batch "openProject(pwd); cd('buildUtilities'); buildtool test({'noHW','bdConnected'})"

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: success() || failure()
        with:
          action_fail: true
          files: |
            results.xml
