name: Package toolbox and publish release

env:
  MATLAB_VER: R2023a

# Run workflow when a tag is created
on:
  push:
    tags: 
      - 'v*'
      
jobs:
  packageToolbox:
    # The type of runner that the job will run on
    runs-on: matlab
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ secrets.REPO_READ_TOKEN }}

      - name: Cache MATLAB build files
        uses: actions/cache@v3
        with:
          key: matlab-buildtool
          path: |
            buildUtilities/.buildtool

      # Download firmware mldatx file from bossdevice-firmware. Must create a step for every MATLAB release to add
      - name: Download R2023a firmware artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.REPO_READ_TOKEN }}
          workflow: main.yml
          repo: sync2brain/bossdevice-firmware
          branch: main
          search_artifacts: true
          name: bossdevice-firmware-R2023a
          path: toolbox/dependencies/firmware
          if_no_artifact_found: fail

      - name: Run MATLAB command
        run: |
          &"$env:ProgramFiles\MATLAB\$env:MATLAB_VER\bin\matlab.exe" -batch "openProject(pwd); cd('buildUtilities'); buildtool test('bdConnected') package('${{  github.ref_name }}','${{  github.actor }}')"
      
      # Create new release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: releases/bossdevice-api-installer.mltbx
          fail_on_unmatched_files: true
          generate_release_notes: true
