name: Package toolbox and publish release

env:
  MATLAB_VER: R2023a

# Run workflow when a tag is created
on:
  push:
    tags: 
      - 'v*'
      
jobs:
  package:
    # The type of runner that the job will run on
    runs-on: matlab
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ secrets.REPO_READ_TOKEN }}

      - name: Cache MATLAB build files
        uses: actions/cache@v3
        with:
          key: cache-matlab
          path: |
            buildUtilities/.buildtool

      - name: Run MATLAB command
        run: |
          &"$env:ProgramFiles\MATLAB\$env:MATLAB_VER\bin\matlab.exe" -batch "openProject(pwd); cd('buildUtilities'); buildtool test('') package('${{  github.ref_name }}','${{  github.actor }}')"
      
      # Create new release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: releases/bossdevice-api-installer.mltbx
          fail_on_unmatched_files: true
          generate_release_notes: true
